//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IECMate.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IECMate.Properties.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\application\\control\\config ähnelt.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Customer\\diagnoseData ähnelt.
        /// </summary>
        internal static string diagnoseData {
            get {
                return ResourceManager.GetString("diagnoseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Customer\\diagramSetup ähnelt.
        /// </summary>
        internal static string diagramSetup {
            get {
                return ResourceManager.GetString("diagramSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die c: ähnelt.
        /// </summary>
        internal static string drive_c {
            get {
                return ResourceManager.GetString("drive_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\contents\\images ähnelt.
        /// </summary>
        internal static string dv_bilder_dev {
            get {
                return ResourceManager.GetString("dv_bilder_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\framework.properties ähnelt.
        /// </summary>
        internal static string dv_framework {
            get {
                return ResourceManager.GetString("dv_framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\PostCheckoutNoPause.bat ähnelt.
        /// </summary>
        internal static string dv_PostCheckoutNoPause {
            get {
                return ResourceManager.GetString("dv_PostCheckoutNoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Tools ähnelt.
        /// </summary>
        internal static string dv_tools {
            get {
                return ResourceManager.GetString("dv_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\media\\usb0\\dataView ähnelt.
        /// </summary>
        internal static string dv_usb_dev {
            get {
                return ResourceManager.GetString("dv_usb_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\view\\media\\usb0\\dataView ähnelt.
        /// </summary>
        internal static string dv_usb_sim {
            get {
                return ResourceManager.GetString("dv_usb_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Customer\\formProgram ähnelt.
        /// </summary>
        internal static string formProgram {
            get {
                return ResourceManager.GetString("formProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\hmiCfg.properties.nt ähnelt.
        /// </summary>
        internal static string hmiCfg {
            get {
                return ResourceManager.GetString("hmiCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\hmiCfg.properties.nt2 ähnelt.
        /// </summary>
        internal static string hmiCfg2 {
            get {
                return ResourceManager.GetString("hmiCfg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\application\\control\\ieccontrol ähnelt.
        /// </summary>
        internal static string ieccontrol {
            get {
                return ResourceManager.GetString("ieccontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Projekt_Datanet\\install ähnelt.
        /// </summary>
        internal static string kundenordner_install {
            get {
                return ResourceManager.GetString("kundenordner_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Log\\IEC_Mate.log ähnelt.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Machine\\machineParameter ähnelt.
        /// </summary>
        internal static string machineParameter {
            get {
                return ResourceManager.GetString("machineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Customer\\machineSetup\\set_MachSetup.xml ähnelt.
        /// </summary>
        internal static string MachSetup {
            get {
                return ResourceManager.GetString("MachSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\update_Dataview_simulation_DB_to_new_vers_and_this_order.bat ähnelt.
        /// </summary>
        internal static string Start_db_update_kundenordner {
            get {
                return ResourceManager.GetString("Start_db_update_kundenordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Start_Simulation.bat ähnelt.
        /// </summary>
        internal static string Start_Simulation {
            get {
                return ResourceManager.GetString("Start_Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Start_Visualization.bat ähnelt.
        /// </summary>
        internal static string Start_Visualization {
            get {
                return ResourceManager.GetString("Start_Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\view\\DataView.exe ähnelt.
        /// </summary>
        internal static string Start_VisualizationDataView {
            get {
                return ResourceManager.GetString("Start_VisualizationDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\Stopp_Simulation.bat ähnelt.
        /// </summary>
        internal static string Stop_Simulation {
            get {
                return ResourceManager.GetString("Stop_Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\data_Machine\\machineSetup\\systemOptions.properties ähnelt.
        /// </summary>
        internal static string systemOptions {
            get {
                return ResourceManager.GetString("systemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\application\\view ähnelt.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
    }
}
