//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IECMate.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IECMate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate ähnelt.
        /// </summary>
        public static string app_titel {
            get {
                return ResourceManager.GetString("app_titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten durch... ähnelt.
        /// </summary>
        public static string cb_var_auswahlen {
            get {
                return ResourceManager.GetString("cb_var_auswahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string dialogDownloadUpdateButton {
            get {
                return ResourceManager.GetString("dialogDownloadUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Backup läuft, bitte warte... ähnelt.
        /// </summary>
        public static string dialogMsgBackup {
            get {
                return ResourceManager.GetString("dialogMsgBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis existiert nicht. ähnelt.
        /// </summary>
        public static string dialogMsgBackupFehler {
            get {
                return ResourceManager.GetString("dialogMsgBackupFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Binär - Eingabe enthält andere Zeichen als 0 oder 1. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetBinFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetBinFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Dezimal - Eingabe enthält andere Zeichen als 0 - 9. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetDezFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetDezFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die eingegebene Zahl ist länger als 32bit. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetGrosseFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetGrosseFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Hex - Eingabe enthält andere Zeichen als 0-9, a-f oder A-F. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetHexFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetHexFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anzahl Variabeln ist nicht identisch. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen00 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Variable in Liste ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen01 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Vorlage fehlt die Variable ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen02 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim generieren vom Code. Variablen und Vorlage überprüfen. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen03 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine Datei auswählen. ähnelt.
        /// </summary>
        public static string dialogMsgDateiOffnenFehler {
            get {
                return ResourceManager.GetString("dialogMsgDateiOffnenFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die eingegebene Zahl ist zu gross. Maximal 2147483647 erlaubt. ähnelt.
        /// </summary>
        public static string dialogMsgDatenbankBitsetFehler {
            get {
                return ResourceManager.GetString("dialogMsgDatenbankBitsetFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zur Datenbank fehlgeschlagen. Bitte MySQL connection string überprüfen. ähnelt.
        /// </summary>
        public static string dialogMsgDatenbankFehler {
            get {
                return ResourceManager.GetString("dialogMsgDatenbankFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Update wird heruntergeladen. Bitte warten... ähnelt.
        /// </summary>
        public static string dialogMsgDownload {
            get {
                return ResourceManager.GetString("dialogMsgDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Download ist Fehlgeschlagen. ähnelt.
        /// </summary>
        public static string dialogMsgDownloadUpdateFehler {
            get {
                return ResourceManager.GetString("dialogMsgDownloadUpdateFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei oder Ordner nicht vorhanden. Bitte den Projektpfad überprüfen. ähnelt.
        /// </summary>
        public static string dialogMsgHelferFehler {
            get {
                return ResourceManager.GetString("dialogMsgHelferFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine ME auswählen. ähnelt.
        /// </summary>
        public static string dialogMsgHelferFehlerME {
            get {
                return ResourceManager.GetString("dialogMsgHelferFehlerME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden alle Dateien mit der Dateiendung *.*Lock gelöscht. Möchten Sie fortfahren? ähnelt.
        /// </summary>
        public static string dialogMsgHelferLock {
            get {
                return ResourceManager.GetString("dialogMsgHelferLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine PX Nummer eingeben. ähnelt.
        /// </summary>
        public static string dialogMsgHotkey {
            get {
                return ResourceManager.GetString("dialogMsgHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Hot Key wird schon verwedent. ähnelt.
        /// </summary>
        public static string dialogMsgHotkeyFehler {
            get {
                return ResourceManager.GetString("dialogMsgHotkeyFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anwendung muss neue gestartet werden um die Sprache zu wechseln. ähnelt.
        /// </summary>
        public static string dialogMsgSpracheUmschalten {
            get {
                return ResourceManager.GetString("dialogMsgSpracheUmschalten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Suche läuft. Bite warten... ähnelt.
        /// </summary>
        public static string dialogMsgSucheLauft {
            get {
                return ResourceManager.GetString("dialogMsgSucheLauft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchfeld ist leer, es sind mehrere Wörter im Suchfeld oder das Verzeichnis existiert nicht. ähnelt.
        /// </summary>
        public static string dialogMsgSucheLeer {
            get {
                return ResourceManager.GetString("dialogMsgSucheLeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis ist kein IEC Projekt. ähnelt.
        /// </summary>
        public static string dialogMsgSucheVerzeichnisFehler {
            get {
                return ResourceManager.GetString("dialogMsgSucheVerzeichnisFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist eine neue Version verfügbar. ähnelt.
        /// </summary>
        public static string dialogMsgUpdate {
            get {
                return ResourceManager.GetString("dialogMsgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string dialogNegButton {
            get {
                return ResourceManager.GetString("dialogNegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup ähnelt.
        /// </summary>
        public static string dialogTitelBackup {
            get {
                return ResourceManager.GetString("dialogTitelBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Eingabe ähnelt.
        /// </summary>
        public static string dialogTitelBitset {
            get {
                return ResourceManager.GetString("dialogTitelBitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen vom Code ähnelt.
        /// </summary>
        public static string dialogTitelCodeGen {
            get {
                return ResourceManager.GetString("dialogTitelCodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen ähnelt.
        /// </summary>
        public static string dialogTitelDateiOffnen {
            get {
                return ResourceManager.GetString("dialogTitelDateiOffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Biteset Fehler ähnelt.
        /// </summary>
        public static string dialogTitelDatenbankFehler {
            get {
                return ResourceManager.GetString("dialogTitelDatenbankFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Update ähnelt.
        /// </summary>
        public static string dialogTitelDownlaod {
            get {
                return ResourceManager.GetString("dialogTitelDownlaod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Fehler ähnelt.
        /// </summary>
        public static string dialogTitelDownloadUpdateFehler {
            get {
                return ResourceManager.GetString("dialogTitelDownloadUpdateFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim öffnen ähnelt.
        /// </summary>
        public static string dialogTitelHelfer {
            get {
                return ResourceManager.GetString("dialogTitelHelfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen von Lock Dateien ähnelt.
        /// </summary>
        public static string dialogTitelHelferLock {
            get {
                return ResourceManager.GetString("dialogTitelHelferLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey ähnelt.
        /// </summary>
        public static string dialogTitelHotkey {
            get {
                return ResourceManager.GetString("dialogTitelHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string dialogTitelSuche {
            get {
                return ResourceManager.GetString("dialogTitelSuche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string dialogTitleUpdate {
            get {
                return ResourceManager.GetString("dialogTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release Seite öffnen ähnelt.
        /// </summary>
        public static string dialogUpdateOffnenButton {
            get {
                return ResourceManager.GetString("dialogUpdateOffnenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string dp_datei {
            get {
                return ResourceManager.GetString("dp_datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string dp_datei_beenden {
            get {
                return ResourceManager.GetString("dp_datei_beenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Speichern ähnelt.
        /// </summary>
        public static string dp_datei_code_speichern {
            get {
                return ResourceManager.GetString("dp_datei_code_speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage Importieren ähnelt.
        /// </summary>
        public static string dp_datei_import {
            get {
                return ResourceManager.GetString("dp_datei_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage Speichern ähnelt.
        /// </summary>
        public static string dp_datei_speichern {
            get {
                return ResourceManager.GetString("dp_datei_speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string dp_hilfe {
            get {
                return ResourceManager.GetString("dp_hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos ähnelt.
        /// </summary>
        public static string dp_hilfe_info {
            get {
                return ResourceManager.GetString("dp_hilfe_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Datei öffnen ähnelt.
        /// </summary>
        public static string dp_hilfe_log {
            get {
                return ResourceManager.GetString("dp_hilfe_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string fo_einstellungen {
            get {
                return ResourceManager.GetString("fo_einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Vorlage ähnelt.
        /// </summary>
        public static string gb_code_vorlage {
            get {
                return ResourceManager.GetString("gb_code_vorlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset Dat@net ähnelt.
        /// </summary>
        public static string gb_datanet_bitset {
            get {
                return ResourceManager.GetString("gb_datanet_bitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Datenbank ähnelt.
        /// </summary>
        public static string gb_dataview_db {
            get {
                return ResourceManager.GetString("gb_dataview_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Datenbank Bitset ähnelt.
        /// </summary>
        public static string gb_dataview_db_bitset {
            get {
                return ResourceManager.GetString("gb_dataview_db_bitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Entwicklung ähnelt.
        /// </summary>
        public static string gb_dataview_dev {
            get {
                return ResourceManager.GetString("gb_dataview_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Simualtion ähnelt.
        /// </summary>
        public static string gb_dataview_sim {
            get {
                return ResourceManager.GetString("gb_dataview_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Globale Funktionen ähnelt.
        /// </summary>
        public static string gb_datei_funktion {
            get {
                return ResourceManager.GetString("gb_datei_funktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decodieren ähnelt.
        /// </summary>
        public static string gb_decoding {
            get {
                return ResourceManager.GetString("gb_decoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encodieren ähnelt.
        /// </summary>
        public static string gb_encoding {
            get {
                return ResourceManager.GetString("gb_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchergebnis ähnelt.
        /// </summary>
        public static string gb_ergebnis {
            get {
                return ResourceManager.GetString("gb_ergebnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktionen für ähnelt.
        /// </summary>
        public static string gb_helfer_funkionen_me {
            get {
                return ResourceManager.GetString("gb_helfer_funkionen_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot Keys ähnelt.
        /// </summary>
        public static string gb_hotkeys {
            get {
                return ResourceManager.GetString("gb_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variablen ähnelt.
        /// </summary>
        public static string gb_variablen {
            get {
                return ResourceManager.GetString("gb_variablen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erste Zeile ähnelt.
        /// </summary>
        public static string header_linie {
            get {
                return ResourceManager.GetString("header_linie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        /// </summary>
        public static string header_typ {
            get {
                return ResourceManager.GetString("header_typ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate auf GitHub ähnelt.
        /// </summary>
        public static string info_link_text {
            get {
                return ResourceManager.GetString("info_link_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string info_titel {
            get {
                return ResourceManager.GetString("info_titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        public static string lanDE {
            get {
                return ResourceManager.GetString("lanDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        public static string lanEN {
            get {
                return ResourceManager.GetString("lanEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aussehen ähnelt.
        /// </summary>
        public static string lb_aussehen {
            get {
                return ResourceManager.GetString("lb_aussehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Projekt ähnelt.
        /// </summary>
        public static string lb_backup {
            get {
                return ResourceManager.GetString("lb_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die config ähnelt.
        /// </summary>
        public static string lb_config {
            get {
                return ResourceManager.GetString("lb_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CTRL + SHIFT + ähnelt.
        /// </summary>
        public static string lb_ctrl_shift {
            get {
                return ResourceManager.GetString("lb_ctrl_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder Ordner öffnen ähnelt.
        /// </summary>
        public static string lb_dataview_bilder_ordner {
            get {
                return ResourceManager.GetString("lb_dataview_bilder_ordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PostCheckoutNoPause.bat ausführen ähnelt.
        /// </summary>
        public static string lb_dataview_PostCheckoutNoPause {
            get {
                return ResourceManager.GetString("lb_dataview_PostCheckoutNoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Simulation deaktivieren ähnelt.
        /// </summary>
        public static string lb_dataview_sim_disable {
            get {
                return ResourceManager.GetString("lb_dataview_sim_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Simulation aktivieren ähnelt.
        /// </summary>
        public static string lb_dataview_sim_enable {
            get {
                return ResourceManager.GetString("lb_dataview_sim_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login als Admin ähnelt.
        /// </summary>
        public static string lb_dataview_start_admin {
            get {
                return ResourceManager.GetString("lb_dataview_start_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halbiert ähnelt.
        /// </summary>
        public static string lb_dataview_start_halb {
            get {
                return ResourceManager.GetString("lb_dataview_start_halb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primär ähnelt.
        /// </summary>
        public static string lb_dataview_start_pri {
            get {
                return ResourceManager.GetString("lb_dataview_start_pri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekundär ähnelt.
        /// </summary>
        public static string lb_dataview_start_sec {
            get {
                return ResourceManager.GetString("lb_dataview_start_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dritt ähnelt.
        /// </summary>
        public static string lb_dataview_start_third {
            get {
                return ResourceManager.GetString("lb_dataview_start_third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login als User ähnelt.
        /// </summary>
        public static string lb_dataview_start_user {
            get {
                return ResourceManager.GetString("lb_dataview_start_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP521 ähnelt.
        /// </summary>
        public static string lb_dataview_start_voll {
            get {
                return ResourceManager.GetString("lb_dataview_start_voll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView Tools öffnen ähnelt.
        /// </summary>
        public static string lb_dataview_tools {
            get {
                return ResourceManager.GetString("lb_dataview_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Datenbank aus Kundenordner ähnelt.
        /// </summary>
        public static string lb_dataview_update_db_kundenordner {
            get {
                return ResourceManager.GetString("lb_dataview_update_db_kundenordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die usb0 Speicher Ordner öffnen ähnelt.
        /// </summary>
        public static string lb_dataview_usb_folder {
            get {
                return ResourceManager.GetString("lb_dataview_usb_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diagnoseData ähnelt.
        /// </summary>
        public static string lb_diagnoseData {
            get {
                return ResourceManager.GetString("lb_diagnoseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diagramSetup ähnelt.
        /// </summary>
        public static string lb_diagramSetup {
            get {
                return ResourceManager.GetString("lb_diagramSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string lb_editor {
            get {
                return ResourceManager.GetString("lb_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die formProgram ähnelt.
        /// </summary>
        public static string lb_formProgram {
            get {
                return ResourceManager.GetString("lb_formProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die framework.properties ähnelt.
        /// </summary>
        public static string lb_framework {
            get {
                return ResourceManager.GetString("lb_framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generieren ähnelt.
        /// </summary>
        public static string lb_genereieren {
            get {
                return ResourceManager.GetString("lb_genereieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate Lizenz: ähnelt.
        /// </summary>
        public static string lb_lizenz {
            get {
                return ResourceManager.GetString("lb_lizenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die machineParameter ähnelt.
        /// </summary>
        public static string lb_machineParameter {
            get {
                return ResourceManager.GetString("lb_machineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set_MachSetup.xml ähnelt.
        /// </summary>
        public static string lb_machineSetup {
            get {
                return ResourceManager.GetString("lb_machineSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC Ordner ähnelt.
        /// </summary>
        public static string lb_me {
            get {
                return ResourceManager.GetString("lb_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type Datei ähnelt.
        /// </summary>
        public static string lb_me_tu {
            get {
                return ResourceManager.GetString("lb_me_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xml Ordner von ähnelt.
        /// </summary>
        public static string lb_me_xml {
            get {
                return ResourceManager.GetString("lb_me_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Source Lizenzen: ähnelt.
        /// </summary>
        public static string lb_oss_lizenz {
            get {
                return ResourceManager.GetString("lb_oss_lizenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Ordner öffnen ähnelt.
        /// </summary>
        public static string lb_pojectFolder {
            get {
                return ResourceManager.GetString("lb_pojectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock Dateien löschen ähnelt.
        /// </summary>
        public static string lb_puLock {
            get {
                return ResourceManager.GetString("lb_puLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 ähnelt.
        /// </summary>
        public static string lb_px {
            get {
                return ResourceManager.GetString("lb_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 begin ähnelt.
        /// </summary>
        public static string lb_px_begin {
            get {
                return ResourceManager.GetString("lb_px_begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt ein Block mit &quot;begin&quot; und &quot;end&quot; ein. ähnelt.
        /// </summary>
        public static string lb_px_beginend {
            get {
                return ResourceManager.GetString("lb_px_beginend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer in Klammern ein. ähnelt.
        /// </summary>
        public static string lb_px_brackets {
            get {
                return ResourceManager.GetString("lb_px_brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (PX05010) ähnelt.
        /// </summary>
        public static string lb_px_brackets_text {
            get {
                return ResourceManager.GetString("lb_px_brackets_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hier kommt der Code; ähnelt.
        /// </summary>
        public static string lb_px_code {
            get {
                return ResourceManager.GetString("lb_px_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer als Kommentar ein. ähnelt.
        /// </summary>
        public static string lb_px_comment {
            get {
                return ResourceManager.GetString("lb_px_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 end ähnelt.
        /// </summary>
        public static string lb_px_end {
            get {
                return ResourceManager.GetString("lb_px_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer ein. ähnelt.
        /// </summary>
        public static string lb_px_plain {
            get {
                return ResourceManager.GetString("lb_px_plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PX05010 ähnelt.
        /// </summary>
        public static string lb_px_plain_text {
            get {
                return ResourceManager.GetString("lb_px_plain_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgrösse ähnelt.
        /// </summary>
        public static string lb_schrift {
            get {
                return ResourceManager.GetString("lb_schrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulation starten ähnelt.
        /// </summary>
        public static string lb_sim {
            get {
                return ResourceManager.GetString("lb_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulation beenden ähnelt.
        /// </summary>
        public static string lb_simStop {
            get {
                return ResourceManager.GetString("lb_simStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string lb_sprache {
            get {
                return ResourceManager.GetString("lb_sprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die systemOptions.properties ähnelt.
        /// </summary>
        public static string lb_systemOptions {
            get {
                return ResourceManager.GetString("lb_systemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 1 ähnelt.
        /// </summary>
        public static string lb_var1 {
            get {
                return ResourceManager.GetString("lb_var1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 2 ähnelt.
        /// </summary>
        public static string lb_var2 {
            get {
                return ResourceManager.GetString("lb_var2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 3 ähnelt.
        /// </summary>
        public static string lb_var3 {
            get {
                return ResourceManager.GetString("lb_var3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nicht installiert ähnelt.
        /// </summary>
        public static string lb_version {
            get {
                return ResourceManager.GetString("lb_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dat@net HMI starten ähnelt.
        /// </summary>
        public static string lb_visu {
            get {
                return ResourceManager.GetString("lb_visu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView HMI starten ähnelt.
        /// </summary>
        public static string lb_visu_dataview {
            get {
                return ResourceManager.GetString("lb_visu_dataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen ähnelt.
        /// </summary>
        public static string mi_datei_offnen {
            get {
                return ResourceManager.GetString("mi_datei_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten Rückgängig ähnelt.
        /// </summary>
        public static string mi_ers_ruck {
            get {
                return ResourceManager.GetString("mi_ers_ruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles in Zwischenablage kopieren ähnelt.
        /// </summary>
        public static string mi_in_clipboard {
            get {
                return ResourceManager.GetString("mi_in_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        public static string mi_pfad_offnen {
            get {
                return ResourceManager.GetString("mi_pfad_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock Dateien wurden gelöscht. ähnelt.
        /// </summary>
        public static string puLockDateien {
            get {
                return ResourceManager.GetString("puLockDateien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchsuchte Dateien:  ähnelt.
        /// </summary>
        public static string suche_dateien {
            get {
                return ResourceManager.GetString("suche_dateien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeile ähnelt.
        /// </summary>
        public static string suche_erster_treffer {
            get {
                return ResourceManager.GetString("suche_erster_treffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gefundene Dateien:  ähnelt.
        /// </summary>
        public static string suche_gefunden {
            get {
                return ResourceManager.GetString("suche_gefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verarbeitungszeit:  ähnelt.
        /// </summary>
        public static string suche_zeit {
            get {
                return ResourceManager.GetString("suche_zeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2#0 ähnelt.
        /// </summary>
        public static string tb_bitset_bin {
            get {
                return ResourceManager.GetString("tb_bitset_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10#, 16# oder 2# Zahl eingeben... ähnelt.
        /// </summary>
        public static string tb_bitset_decode {
            get {
                return ResourceManager.GetString("tb_bitset_decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        public static string tb_bitset_dez {
            get {
                return ResourceManager.GetString("tb_bitset_dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 16#0 ähnelt.
        /// </summary>
        public static string tb_bitset_hex {
            get {
                return ResourceManager.GetString("tb_bitset_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MySQL connection string ähnelt.
        /// </summary>
        public static string tb_db_connectionstring {
            get {
                return ResourceManager.GetString("tb_db_connectionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten durch: ähnelt.
        /// </summary>
        public static string tb_ersetzten_druch {
            get {
                return ResourceManager.GetString("tb_ersetzten_druch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PE39 ähnelt.
        /// </summary>
        public static string tb_kundenspez {
            get {
                return ResourceManager.GetString("tb_kundenspez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neuer Bitset (Dezimalzahl) ähnelt.
        /// </summary>
        public static string tb_kundenspez_update {
            get {
                return ResourceManager.GetString("tb_kundenspez_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Ordner auswählen... ähnelt.
        /// </summary>
        public static string tb_proj_auswahlen {
            get {
                return ResourceManager.GetString("tb_proj_auswahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kundenordner auswählen... ähnelt.
        /// </summary>
        public static string tb_proj_kundenordner {
            get {
                return ResourceManager.GetString("tb_proj_kundenordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PX Nummer eingeben... ähnelt.
        /// </summary>
        public static string tb_px_nummer {
            get {
                return ResourceManager.GetString("tb_px_nummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen nach... ähnelt.
        /// </summary>
        public static string tb_suchen_nach {
            get {
                return ResourceManager.GetString("tb_suchen_nach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen nach... (Strg + F) ähnelt.
        /// </summary>
        public static string tb_suchen_nach_code {
            get {
                return ResourceManager.GetString("tb_suchen_nach_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variablen hier einfügen... ähnelt.
        /// </summary>
        public static string tb_var_einfügen {
            get {
                return ResourceManager.GetString("tb_var_einfügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot Key verwenden ähnelt.
        /// </summary>
        public static string tg_hotkey_ein {
            get {
                return ResourceManager.GetString("tg_hotkey_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerzeichen anzeigen ähnelt.
        /// </summary>
        public static string tg_leer_ein {
            get {
                return ResourceManager.GetString("tg_leer_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilennummern anzeigen ähnelt.
        /// </summary>
        public static string tg_line_ein {
            get {
                return ResourceManager.GetString("tg_line_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabs in Leerezeichen umwandeln ähnelt.
        /// </summary>
        public static string tg_spaceumwandeln {
            get {
                return ResourceManager.GetString("tg_spaceumwandeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        /// </summary>
        public static string tg_theme_dunkel {
            get {
                return ResourceManager.GetString("tg_theme_dunkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        /// </summary>
        public static string tg_theme_hell {
            get {
                return ResourceManager.GetString("tg_theme_hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab anzeigen ähnelt.
        /// </summary>
        public static string tg_zeigetab {
            get {
                return ResourceManager.GetString("tg_zeigetab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilenende anzeigen ähnelt.
        /// </summary>
        public static string tg_zeigezeilenende {
            get {
                return ResourceManager.GetString("tg_zeigezeilenende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset ähnelt.
        /// </summary>
        public static string ti_bitset {
            get {
                return ResourceManager.GetString("ti_bitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code ähnelt.
        /// </summary>
        public static string ti_code {
            get {
                return ResourceManager.GetString("ti_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dat@net ähnelt.
        /// </summary>
        public static string ti_helfer {
            get {
                return ResourceManager.GetString("ti_helfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helfer ähnelt.
        /// </summary>
        public static string ti_helfer_alg {
            get {
                return ResourceManager.GetString("ti_helfer_alg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DataView ähnelt.
        /// </summary>
        public static string ti_helfer_dataview {
            get {
                return ResourceManager.GetString("ti_helfer_dataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string ti_suche {
            get {
                return ResourceManager.GetString("ti_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dateitypen durchsuchen ähnelt.
        /// </summary>
        public static string ts_bin_ein {
            get {
                return ResourceManager.GetString("ts_bin_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ganzes Wort suchen ähnelt.
        /// </summary>
        public static string ts_exakte_ein {
            get {
                return ResourceManager.GetString("ts_exakte_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur Verzeichnis \config durchsuchen ähnelt.
        /// </summary>
        public static string ts_hw_ein {
            get {
                return ResourceManager.GetString("ts_hw_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchvorschlag für HW Endpunkte ähnelt.
        /// </summary>
        public static string ts_hw_vorschalg {
            get {
                return ResourceManager.GetString("ts_hw_vorschalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur *.java Dateien durchsuchen ähnelt.
        /// </summary>
        public static string ts_java_suche {
            get {
                return ResourceManager.GetString("ts_java_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien mit Notepad++ öffnen ähnelt.
        /// </summary>
        public static string ts_offnen_nppp {
            get {
                return ResourceManager.GetString("ts_offnen_nppp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur Mask *.xml Dateien durchsuchen ähnelt.
        /// </summary>
        public static string ts_xml_suche {
            get {
                return ResourceManager.GetString("ts_xml_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksumme aus systemOptions.properties abrufen. ähnelt.
        /// </summary>
        public static string tt_checksum_datanet {
            get {
                return ResourceManager.GetString("tt_checksum_datanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopiert den kompletten Code in die Zwischenablage. ähnelt.
        /// </summary>
        public static string tt_code_gen_copy {
            get {
                return ResourceManager.GetString("tt_code_gen_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviert den automatischen start der DataView Visualisierung in Start_Simulation.bat ähnelt.
        /// </summary>
        public static string tt_dataview_sim_disable {
            get {
                return ResourceManager.GetString("tt_dataview_sim_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviert den automatischen start der DataView Visualisierung in Start_Simulation.bat ähnelt.
        /// </summary>
        public static string tt_dataview_sim_enable {
            get {
                return ResourceManager.GetString("tt_dataview_sim_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setzt den Parameter &quot;startAdminUser&quot; in framework.properties ähnelt.
        /// </summary>
        public static string tt_dataview_start_admin {
            get {
                return ResourceManager.GetString("tt_dataview_start_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setzt den Parameter &quot;fx-stage-screen&quot; in framework.properties ähnelt.
        /// </summary>
        public static string tt_dataview_start_pri {
            get {
                return ResourceManager.GetString("tt_dataview_start_pri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setzt den Parameter &quot;resolution&quot; in framework.properties ähnelt.
        /// </summary>
        public static string tt_dataview_start_voll {
            get {
                return ResourceManager.GetString("tt_dataview_start_voll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update_Dataview_sim****.bat aus Kundenordner ausführen ähnelt.
        /// </summary>
        public static string tt_dataview_update_db_kundenordner {
            get {
                return ResourceManager.GetString("tt_dataview_update_db_kundenordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macht das ersetzten wieder Rückgangig. ähnelt.
        /// </summary>
        public static string tt_ers_ruck {
            get {
                return ResourceManager.GetString("tt_ers_ruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten ähnelt.
        /// </summary>
        public static string tt_ersetzten {
            get {
                return ResourceManager.GetString("tt_ersetzten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle ersetzten ähnelt.
        /// </summary>
        public static string tt_ersetzten_alle {
            get {
                return ResourceManager.GetString("tt_ersetzten_alle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiendungen die bei der Suche ausgeschlossen werden. ähnelt.
        /// </summary>
        public static string tt_file_ext {
            get {
                return ResourceManager.GetString("tt_file_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardwerte wiederherstellen. ähnelt.
        /// </summary>
        public static string tt_file_ext_default {
            get {
                return ResourceManager.GetString("tt_file_ext_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn die konfigurierte Tastenkombination gedrückt wird, dann wird automatisch der Text eingefügt. ähnelt.
        /// </summary>
        public static string tt_hotkey {
            get {
                return ResourceManager.GetString("tt_hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird ein Suchvorschlag für alle HW Endpunkte im Verzeichnis .\application\control\config angezeigt. ähnelt.
        /// </summary>
        public static string tt_hw_vorschlag {
            get {
                return ResourceManager.GetString("tt_hw_vorschlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden nur *.java Dateien durchsucht auch wenn diese ausgeschlossen wurden. ähnelt.
        /// </summary>
        public static string tt_java_suche {
            get {
                return ResourceManager.GetString("tt_java_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset aus der Datenbank für den Kundenspez abrufen. ähnelt.
        /// </summary>
        public static string tt_kundenspez {
            get {
                return ResourceManager.GetString("tt_kundenspez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksumme auf den Wert -1 setzten. ähnelt.
        /// </summary>
        public static string tt_kundenspez_checksum_datanet {
            get {
                return ResourceManager.GetString("tt_kundenspez_checksum_datanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset aus systemOptions.properties für den Kundenspez abrufen. ähnelt.
        /// </summary>
        public static string tt_kundenspez_datanet {
            get {
                return ResourceManager.GetString("tt_kundenspez_datanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset decodieren. ähnelt.
        /// </summary>
        public static string tt_kundenspez_decodieren {
            get {
                return ResourceManager.GetString("tt_kundenspez_decodieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset in der Datenbank für den Kundenspez ändern (Dezimalzahl). ähnelt.
        /// </summary>
        public static string tt_kundenspez_update {
            get {
                return ResourceManager.GetString("tt_kundenspez_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset in systemOptions.properties für den Kundenspez ändern (Dezimalzahl). ähnelt.
        /// </summary>
        public static string tt_kundenspez_update_datanet {
            get {
                return ResourceManager.GetString("tt_kundenspez_update_datanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Dokument wird automatisch bei der richtigen Zeile mit Notepad++ geöffnet. ähnelt.
        /// </summary>
        public static string tt_offnen_nppp {
            get {
                return ResourceManager.GetString("tt_offnen_nppp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die z.B. \\uzn343\dc_gbf_dat\Kunden_Datanet\BDAG_DE3\9990214612 ähnelt.
        /// </summary>
        public static string tt_proj_kundenordner {
            get {
                return ResourceManager.GetString("tt_proj_kundenordner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startet die Simulation im angegebenen Projektverzeichnis. ähnelt.
        /// </summary>
        public static string tt_sim_start {
            get {
                return ResourceManager.GetString("tt_sim_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopt die Prozesse &quot;K2Ctrl&quot;, &quot;putty&quot;, &quot;DataView&quot;, &quot;java&quot; und &quot;cmd&quot;. Dies kann auch unbeabsichtigt andere Programme beenden. ähnelt.
        /// </summary>
        public static string tt_stop_sim {
            get {
                return ResourceManager.GetString("tt_stop_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden auch die ausgeschlossenen Dateitypen durchsucht. ähnelt.
        /// </summary>
        public static string tt_suche_bin {
            get {
                return ResourceManager.GetString("tt_suche_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird nach dem ganzen Wort gesucht. ähnelt.
        /// </summary>
        public static string tt_suche_exakt {
            get {
                return ResourceManager.GetString("tt_suche_exakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sucht nur im Unterverzeichnis \application\control\config\. ähnelt.
        /// </summary>
        public static string tt_suche_hw {
            get {
                return ResourceManager.GetString("tt_suche_hw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählte Datei öffnen. ähnelt.
        /// </summary>
        public static string tt_suche_offnen {
            get {
                return ResourceManager.GetString("tt_suche_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name der Batch Datei für das Datenbank Update im Kundenordner\Projekt_Datanet\install ähnelt.
        /// </summary>
        public static string tt_updateBat {
            get {
                return ResourceManager.GetString("tt_updateBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startet eine Dat@net Visualisierung im angegebenen Projektverzeichnis. ähnelt.
        /// </summary>
        public static string tt_visu_datanet {
            get {
                return ResourceManager.GetString("tt_visu_datanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startet eine DataView Visualisierung im angegebenen Projektverzeichnis. ähnelt.
        /// </summary>
        public static string tt_visu_dataview {
            get {
                return ResourceManager.GetString("tt_visu_dataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden nur *.xml Datein im Verzeichnis application\view\me\hmi\text durchsucht. ähnelt.
        /// </summary>
        public static string tt_xml_suche {
            get {
                return ResourceManager.GetString("tt_xml_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset zum Encodieren verschieben. ähnelt.
        /// </summary>
        public static string tt_zu_encodieng_kopieren {
            get {
                return ResourceManager.GetString("tt_zu_encodieng_kopieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine ME auswählen... ähnelt.
        /// </summary>
        public static string wm_cb_me_auswahlen {
            get {
                return ResourceManager.GetString("wm_cb_me_auswahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiendungen eintragen... ähnelt.
        /// </summary>
        public static string wm_file_ext {
            get {
                return ResourceManager.GetString("wm_file_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skript Name (update_Dataview_simu****.bat) ähnelt.
        /// </summary>
        public static string wm_updateBat {
            get {
                return ResourceManager.GetString("wm_updateBat", resourceCulture);
            }
        }
    }
}
