//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IECMate.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IECMate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate ähnelt.
        /// </summary>
        public static string app_titel {
            get {
                return ResourceManager.GetString("app_titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten durch... ähnelt.
        /// </summary>
        public static string cb_var_auswahlen {
            get {
                return ResourceManager.GetString("cb_var_auswahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Update ähnelt.
        /// </summary>
        public static string dialogDownloadUpdateButton {
            get {
                return ResourceManager.GetString("dialogDownloadUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Backup läuft, bitte warte... ähnelt.
        /// </summary>
        public static string dialogMsgBackup {
            get {
                return ResourceManager.GetString("dialogMsgBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis existiert nicht. ähnelt.
        /// </summary>
        public static string dialogMsgBackupFehler {
            get {
                return ResourceManager.GetString("dialogMsgBackupFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Binär - Eingabe enthält andere Zeichen als 0 oder 1. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetBinFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetBinFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Dezimal - Eingabe enthält andere Zeichen als 0 - 9. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetDezFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetDezFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die eingegebene Zahl ist länger als 32bit. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetGrosseFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetGrosseFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Hex - Eingabe enthält andere Zeichen als 0-9, a-f oder A-F. ähnelt.
        /// </summary>
        public static string dialogMsgBitsetHexFehler {
            get {
                return ResourceManager.GetString("dialogMsgBitsetHexFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; Die Anzahl Variabeln ist nicht identisch. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen00 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; Keine Variable in Liste 1. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen01 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; Keine Variable in Liste 2. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen02 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; Keine Variable in Liste 3. ähnelt.
        /// </summary>
        public static string dialogMsgCodeGen03 {
            get {
                return ResourceManager.GetString("dialogMsgCodeGen03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine Datei auswählen. ähnelt.
        /// </summary>
        public static string dialogMsgDateiOffnenFehler {
            get {
                return ResourceManager.GetString("dialogMsgDateiOffnenFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei oder  Ordner nicht vorhanden. Bitte den Projektpfad überprüfen. ähnelt.
        /// </summary>
        public static string dialogMsgHelferFehler {
            get {
                return ResourceManager.GetString("dialogMsgHelferFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine ME auswählen. ähnelt.
        /// </summary>
        public static string dialogMsgHelferFehlerME {
            get {
                return ResourceManager.GetString("dialogMsgHelferFehlerME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden alle Datein mit der Dateiendung *.puLock gelöscht. Möchten Sie fortfahren? ähnelt.
        /// </summary>
        public static string dialogMsgHelferLock {
            get {
                return ResourceManager.GetString("dialogMsgHelferLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine PX Nummer eingeben. ähnelt.
        /// </summary>
        public static string dialogMsgHotkey {
            get {
                return ResourceManager.GetString("dialogMsgHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Hot Key wird schon verwedent. ähnelt.
        /// </summary>
        public static string dialogMsgHotkeyFehler {
            get {
                return ResourceManager.GetString("dialogMsgHotkeyFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anwendung muss neue gestartet werden um die Sprache zu wechseln. ähnelt.
        /// </summary>
        public static string dialogMsgSpracheUmschalten {
            get {
                return ResourceManager.GetString("dialogMsgSpracheUmschalten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Suche läuft. Bite warten... ähnelt.
        /// </summary>
        public static string dialogMsgSucheLauft {
            get {
                return ResourceManager.GetString("dialogMsgSucheLauft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchfeld ist leer, es sind mehrere Wörter im Suchfeld oder das Verzeichnis existiert nicht. ähnelt.
        /// </summary>
        public static string dialogMsgSucheLeer {
            get {
                return ResourceManager.GetString("dialogMsgSucheLeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis ist kein IEC Projekt. ähnelt.
        /// </summary>
        public static string dialogMsgSucheVerzeichnisFehler {
            get {
                return ResourceManager.GetString("dialogMsgSucheVerzeichnisFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist eine neue Version verfügbar. ähnelt.
        /// </summary>
        public static string dialogMsgUpdate {
            get {
                return ResourceManager.GetString("dialogMsgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string dialogNegButton {
            get {
                return ResourceManager.GetString("dialogNegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup ähnelt.
        /// </summary>
        public static string dialogTitelBackup {
            get {
                return ResourceManager.GetString("dialogTitelBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Eingabe ähnelt.
        /// </summary>
        public static string dialogTitelBitset {
            get {
                return ResourceManager.GetString("dialogTitelBitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen vom Code ähnelt.
        /// </summary>
        public static string dialogTitelCodeGen {
            get {
                return ResourceManager.GetString("dialogTitelCodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen ähnelt.
        /// </summary>
        public static string dialogTitelDateiOffnen {
            get {
                return ResourceManager.GetString("dialogTitelDateiOffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim öffnen ähnelt.
        /// </summary>
        public static string dialogTitelHelfer {
            get {
                return ResourceManager.GetString("dialogTitelHelfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen von puLock Datein ähnelt.
        /// </summary>
        public static string dialogTitelHelferLock {
            get {
                return ResourceManager.GetString("dialogTitelHelferLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey ähnelt.
        /// </summary>
        public static string dialogTitelHotkey {
            get {
                return ResourceManager.GetString("dialogTitelHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string dialogTitelSuche {
            get {
                return ResourceManager.GetString("dialogTitelSuche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string dialogTitleUpdate {
            get {
                return ResourceManager.GetString("dialogTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Seite öffnen ähnelt.
        /// </summary>
        public static string dialogUpdateOffnenButton {
            get {
                return ResourceManager.GetString("dialogUpdateOffnenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string dp_datei {
            get {
                return ResourceManager.GetString("dp_datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string dp_datei_beenden {
            get {
                return ResourceManager.GetString("dp_datei_beenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Speichern ähnelt.
        /// </summary>
        public static string dp_datei_code_speichern {
            get {
                return ResourceManager.GetString("dp_datei_code_speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage Importieren ähnelt.
        /// </summary>
        public static string dp_datei_import {
            get {
                return ResourceManager.GetString("dp_datei_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage Speichern ähnelt.
        /// </summary>
        public static string dp_datei_speichern {
            get {
                return ResourceManager.GetString("dp_datei_speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string dp_hilfe {
            get {
                return ResourceManager.GetString("dp_hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos ähnelt.
        /// </summary>
        public static string dp_hilfe_info {
            get {
                return ResourceManager.GetString("dp_hilfe_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string fo_einstellungen {
            get {
                return ResourceManager.GetString("fo_einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Vorlage ähnelt.
        /// </summary>
        public static string gb_code_vorlage {
            get {
                return ResourceManager.GetString("gb_code_vorlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Globale Funktionen ähnelt.
        /// </summary>
        public static string gb_datei_funktion {
            get {
                return ResourceManager.GetString("gb_datei_funktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decodieren ähnelt.
        /// </summary>
        public static string gb_decoding {
            get {
                return ResourceManager.GetString("gb_decoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encodieren ähnelt.
        /// </summary>
        public static string gb_encoding {
            get {
                return ResourceManager.GetString("gb_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchergebnis ähnelt.
        /// </summary>
        public static string gb_ergebnis {
            get {
                return ResourceManager.GetString("gb_ergebnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktion für ME ähnelt.
        /// </summary>
        public static string gb_helfer_funkionen_me {
            get {
                return ResourceManager.GetString("gb_helfer_funkionen_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot Keys ähnelt.
        /// </summary>
        public static string gb_hotkeys {
            get {
                return ResourceManager.GetString("gb_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variablen ähnelt.
        /// </summary>
        public static string gb_variablen {
            get {
                return ResourceManager.GetString("gb_variablen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate auf GitHub ähnelt.
        /// </summary>
        public static string info_link_text {
            get {
                return ResourceManager.GetString("info_link_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string info_titel {
            get {
                return ResourceManager.GetString("info_titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        public static string lanDE {
            get {
                return ResourceManager.GetString("lanDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        public static string lanEN {
            get {
                return ResourceManager.GetString("lanEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aussehen ähnelt.
        /// </summary>
        public static string lb_aussehen {
            get {
                return ResourceManager.GetString("lb_aussehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Projekt ähnelt.
        /// </summary>
        public static string lb_backup {
            get {
                return ResourceManager.GetString("lb_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die config ähnelt.
        /// </summary>
        public static string lb_config {
            get {
                return ResourceManager.GetString("lb_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CTRL + SHIFT + ähnelt.
        /// </summary>
        public static string lb_ctrl_shift {
            get {
                return ResourceManager.GetString("lb_ctrl_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diagnoseData ähnelt.
        /// </summary>
        public static string lb_diagnoseData {
            get {
                return ResourceManager.GetString("lb_diagnoseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diagramSetup ähnelt.
        /// </summary>
        public static string lb_diagramSetup {
            get {
                return ResourceManager.GetString("lb_diagramSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string lb_editor {
            get {
                return ResourceManager.GetString("lb_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die formProgram ähnelt.
        /// </summary>
        public static string lb_formProgram {
            get {
                return ResourceManager.GetString("lb_formProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generieren ähnelt.
        /// </summary>
        public static string lb_genereieren {
            get {
                return ResourceManager.GetString("lb_genereieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEC-Mate Lizenz: ähnelt.
        /// </summary>
        public static string lb_lizenz {
            get {
                return ResourceManager.GetString("lb_lizenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die machineParameter ähnelt.
        /// </summary>
        public static string lb_machineParameter {
            get {
                return ResourceManager.GetString("lb_machineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set_MachSetup.xml ähnelt.
        /// </summary>
        public static string lb_machineSetup {
            get {
                return ResourceManager.GetString("lb_machineSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ME Ordner ähnelt.
        /// </summary>
        public static string lb_me {
            get {
                return ResourceManager.GetString("lb_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xml der ME ähnelt.
        /// </summary>
        public static string lb_me_xml {
            get {
                return ResourceManager.GetString("lb_me_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Source Lizenzen: ähnelt.
        /// </summary>
        public static string lb_oss_lizenz {
            get {
                return ResourceManager.GetString("lb_oss_lizenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Ordner ähnelt.
        /// </summary>
        public static string lb_pojectFolder {
            get {
                return ResourceManager.GetString("lb_pojectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die puLock Datein löschen ähnelt.
        /// </summary>
        public static string lb_puLock {
            get {
                return ResourceManager.GetString("lb_puLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 ähnelt.
        /// </summary>
        public static string lb_px {
            get {
                return ResourceManager.GetString("lb_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 begin ähnelt.
        /// </summary>
        public static string lb_px_begin {
            get {
                return ResourceManager.GetString("lb_px_begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt ein Block mit &quot;begin&quot; und &quot;end&quot; ein. ähnelt.
        /// </summary>
        public static string lb_px_beginend {
            get {
                return ResourceManager.GetString("lb_px_beginend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer in Klammern ein. ähnelt.
        /// </summary>
        public static string lb_px_brackets {
            get {
                return ResourceManager.GetString("lb_px_brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (PX05010) ähnelt.
        /// </summary>
        public static string lb_px_brackets_text {
            get {
                return ResourceManager.GetString("lb_px_brackets_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hier kommt der Code; ähnelt.
        /// </summary>
        public static string lb_px_code {
            get {
                return ResourceManager.GetString("lb_px_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer als Kommentar ein. ähnelt.
        /// </summary>
        public static string lb_px_comment {
            get {
                return ResourceManager.GetString("lb_px_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // PX05010 end ähnelt.
        /// </summary>
        public static string lb_px_end {
            get {
                return ResourceManager.GetString("lb_px_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügt die PX Nummer ein. ähnelt.
        /// </summary>
        public static string lb_px_plain {
            get {
                return ResourceManager.GetString("lb_px_plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PX05010 ähnelt.
        /// </summary>
        public static string lb_px_plain_text {
            get {
                return ResourceManager.GetString("lb_px_plain_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgrösse ähnelt.
        /// </summary>
        public static string lb_schrift {
            get {
                return ResourceManager.GetString("lb_schrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulation starten ähnelt.
        /// </summary>
        public static string lb_sim {
            get {
                return ResourceManager.GetString("lb_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string lb_sprache {
            get {
                return ResourceManager.GetString("lb_sprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die systemOptions.properties ähnelt.
        /// </summary>
        public static string lb_systemOptions {
            get {
                return ResourceManager.GetString("lb_systemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 1 ähnelt.
        /// </summary>
        public static string lb_var1 {
            get {
                return ResourceManager.GetString("lb_var1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 2 ähnelt.
        /// </summary>
        public static string lb_var2 {
            get {
                return ResourceManager.GetString("lb_var2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VARIABLE 3 ähnelt.
        /// </summary>
        public static string lb_var3 {
            get {
                return ResourceManager.GetString("lb_var3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nicht installiert ähnelt.
        /// </summary>
        public static string lb_version {
            get {
                return ResourceManager.GetString("lb_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualisierung starten ähnelt.
        /// </summary>
        public static string lb_visu {
            get {
                return ResourceManager.GetString("lb_visu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen ähnelt.
        /// </summary>
        public static string mi_datei_offnen {
            get {
                return ResourceManager.GetString("mi_datei_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten Rückgängig ähnelt.
        /// </summary>
        public static string mi_ers_ruck {
            get {
                return ResourceManager.GetString("mi_ers_ruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles in Zwischenablage kopieren ähnelt.
        /// </summary>
        public static string mi_in_clipboard {
            get {
                return ResourceManager.GetString("mi_in_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        public static string mi_pfad_offnen {
            get {
                return ResourceManager.GetString("mi_pfad_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchsuchte Dateien:  ähnelt.
        /// </summary>
        public static string suche_dateien {
            get {
                return ResourceManager.GetString("suche_dateien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gefundene Dateien:  ähnelt.
        /// </summary>
        public static string suche_gefunden {
            get {
                return ResourceManager.GetString("suche_gefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verarbeitungszeit:  ähnelt.
        /// </summary>
        public static string suche_zeit {
            get {
                return ResourceManager.GetString("suche_zeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2#0 ähnelt.
        /// </summary>
        public static string tb_bitset_bin {
            get {
                return ResourceManager.GetString("tb_bitset_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10#, 16# oder 2# Zahl eingeben... ähnelt.
        /// </summary>
        public static string tb_bitset_decode {
            get {
                return ResourceManager.GetString("tb_bitset_decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        public static string tb_bitset_dez {
            get {
                return ResourceManager.GetString("tb_bitset_dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 16#0 ähnelt.
        /// </summary>
        public static string tb_bitset_hex {
            get {
                return ResourceManager.GetString("tb_bitset_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzten durch: ähnelt.
        /// </summary>
        public static string tb_ersetzten_druch {
            get {
                return ResourceManager.GetString("tb_ersetzten_druch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Ordner auswählen... ähnelt.
        /// </summary>
        public static string tb_proj_auswahlen {
            get {
                return ResourceManager.GetString("tb_proj_auswahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PX Nummer eingeben... ähnelt.
        /// </summary>
        public static string tb_px_nummer {
            get {
                return ResourceManager.GetString("tb_px_nummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen nach... ähnelt.
        /// </summary>
        public static string tb_suchen_nach {
            get {
                return ResourceManager.GetString("tb_suchen_nach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variablen hier einfügen... ähnelt.
        /// </summary>
        public static string tb_var_einfügen {
            get {
                return ResourceManager.GetString("tb_var_einfügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot Key verwenden ähnelt.
        /// </summary>
        public static string tg_hotkey_ein {
            get {
                return ResourceManager.GetString("tg_hotkey_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerzeichen anzeigen ähnelt.
        /// </summary>
        public static string tg_leer_ein {
            get {
                return ResourceManager.GetString("tg_leer_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilennummern anzeigen ähnelt.
        /// </summary>
        public static string tg_line_ein {
            get {
                return ResourceManager.GetString("tg_line_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabs in Leerezeichen umwandeln ähnelt.
        /// </summary>
        public static string tg_spaceumwandeln {
            get {
                return ResourceManager.GetString("tg_spaceumwandeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        /// </summary>
        public static string tg_theme_dunkel {
            get {
                return ResourceManager.GetString("tg_theme_dunkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        /// </summary>
        public static string tg_theme_hell {
            get {
                return ResourceManager.GetString("tg_theme_hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab anzeigen ähnelt.
        /// </summary>
        public static string tg_zeigetab {
            get {
                return ResourceManager.GetString("tg_zeigetab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilenende anzeigen ähnelt.
        /// </summary>
        public static string tg_zeigezeilenende {
            get {
                return ResourceManager.GetString("tg_zeigezeilenende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitset ähnelt.
        /// </summary>
        public static string ti_bitset {
            get {
                return ResourceManager.GetString("ti_bitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code ähnelt.
        /// </summary>
        public static string ti_code {
            get {
                return ResourceManager.GetString("ti_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helfer ähnelt.
        /// </summary>
        public static string ti_helfer {
            get {
                return ResourceManager.GetString("ti_helfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string ti_suche {
            get {
                return ResourceManager.GetString("ti_suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateitypen durchsuchen ähnelt.
        /// </summary>
        public static string ts_bin_ein {
            get {
                return ResourceManager.GetString("ts_bin_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ganzes Wort suchen ähnelt.
        /// </summary>
        public static string ts_exakte_ein {
            get {
                return ResourceManager.GetString("ts_exakte_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur in HW-Konfig suchen ähnelt.
        /// </summary>
        public static string ts_hw_ein {
            get {
                return ResourceManager.GetString("ts_hw_ein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchvorschlag für HW Endpunkte ähnelt.
        /// </summary>
        public static string ts_hw_vorschalg {
            get {
                return ResourceManager.GetString("ts_hw_vorschalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopiert den kompletten Code in die Zwischenablage. ähnelt.
        /// </summary>
        public static string tt_code_gen_copy {
            get {
                return ResourceManager.GetString("tt_code_gen_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macht das ersetzten wieder Rückgangig. ähnelt.
        /// </summary>
        public static string tt_ers_ruck {
            get {
                return ResourceManager.GetString("tt_ers_ruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiendungen die bei der Suche ausgeschlossen werden. ähnelt.
        /// </summary>
        public static string tt_file_ext {
            get {
                return ResourceManager.GetString("tt_file_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardwerte wiederherstellen. ähnelt.
        /// </summary>
        public static string tt_file_ext_default {
            get {
                return ResourceManager.GetString("tt_file_ext_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn die konfigurierte Tastenkombination gedrückt wird, dann wird automatisch der Text eingefügt. ähnelt.
        /// </summary>
        public static string tt_hotkey {
            get {
                return ResourceManager.GetString("tt_hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird ein Suchvorschlag für alle HW Endpunkte im Verzeichnis .\application\control\config angezeigt. ähnelt.
        /// </summary>
        public static string tt_hw_vorschlag {
            get {
                return ResourceManager.GetString("tt_hw_vorschlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden auch die ausgeschlossenen Dateitypen durchsucht. ähnelt.
        /// </summary>
        public static string tt_suche_bin {
            get {
                return ResourceManager.GetString("tt_suche_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird nach dem ganzen Wort gesucht. ähnelt.
        /// </summary>
        public static string tt_suche_exakt {
            get {
                return ResourceManager.GetString("tt_suche_exakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sucht nur im Unterverzeichnis \application\control\config\. ähnelt.
        /// </summary>
        public static string tt_suche_hw {
            get {
                return ResourceManager.GetString("tt_suche_hw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählte Datei öffnen. ähnelt.
        /// </summary>
        public static string tt_suche_offnen {
            get {
                return ResourceManager.GetString("tt_suche_offnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiendungen eintragen... ähnelt.
        /// </summary>
        public static string wm_file_ext {
            get {
                return ResourceManager.GetString("wm_file_ext", resourceCulture);
            }
        }
    }
}
